SHOW TABLES;
SELECT * from Transactions;
SELECT * from Traveler;
SELECT * from Agent;
SELECT * from Package;
SELECT * FROM Travel;
SELECT * from Agency WHERE Agency_ID = 1;
SELECT * from Destination WHERE Destination_ID = 10;
SELECT * from Reviews where Review_ID = 3;
SELECT * from Agent WHERE Agent_ID = 5;
SELECT * from Transactions where Transaction_ID = 9;
SELECT * from Hotels where Hotel_ID in (101,103,105,107);
SELECT * from Destination where Destination_ID in (2, 4, 6, 8);
SELECT * from Reviews where Review_ID in (4,2,3,6,1);
SELECT * from Travel where Travel_ID in (5,2,3,9);
SELECT * from Agency where Agency_name="Safari Quest";
SELECT * from Package where Duration=7;
SELECT * from Trip WHERE Booking_date='2023-01-01';
SELECT * from Traveler where Traveler_ID=3;
SELECT * from Transactions where Payment_Status='Pending' AND Payment_Method = 'Bank Transfer';
